version: 2.1

aliases:
  - &jfrog-login
    name: Rename jfrog environment variable for maven setting.xml
    command: |
      echo "export JFROG_USER=$ARTIFACTORY_USER"  >> $BASH_ENV
      echo "export JFROG_PASS=$ARTIFACTORY_PASSWORD"  >> $BASH_ENV

  - &release
    name: Release
    command: |
      if [ "$(git log -n 1 --pretty="%an")" == "Renovate Bot" ]
      then
        echo "Skipping release"
      else
      echo "Start release"
      git config --global user.email "circleci@entur.no"
      git config --global user.name "circleci"
      git checkout master
      mvn gitflow:release-start gitflow:release-finish -DskipTests=true -Prelease -DpostReleaseGoals=deploy -DargLine='-Prelease -DskipTests' -B
      fi

  - &import_gpg_key
    name: Configure GPG private key for signing project artifacts in OSS Sonatype
    command: |
      echo $SONATYPE_GPG_KEY_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes

  - &maven-settings-file
      "\"<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd' xmlns='http://maven.apache.org/SETTINGS/1.1.0'
                xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
              <servers>
                <server>
                  <username>$SONATYPE_USERNAME</username>
                  <password>$SONATYPE_PASSWORD</password>
                  <id>ossrh</id>
                </server>
              </servers>
            </settings>\""

commands:
  generate-maven-settings-file:
    parameters:
      settings-file:
        type: string
    steps:
      - run:
          name: Generate Maven Settings File
          command: |
            mkdir -p ~/.m2
            echo -e << parameters.settings-file >> > ~/.m2/settings.xml

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - generate-maven-settings-file:
          settings-file: *maven-settings-file
      - restore_cache:
          keys:
            - dep-cache-v2-{{ checksum "pom.xml" }}
      - run: *jfrog-login
      - run:
          name: Refresh cache
          command: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: dep-cache-v2-{{ checksum "pom.xml" }}
      # Cannot use -o because of snapshot dependencies.
      - run: mvn package -s .circleci/settings.xml
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - persist_to_workspace:
          root: ~/project
          paths:
            - target
      - run: mvn verify
      - run: *import_gpg_key
      - run: *release

  deploy:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-v2-{{ checksum "pom.xml" }}
      - run:
          name: Download Maven settings
          command: wget https://raw.githubusercontent.com/entur/circleci-toolbox-image-java11/master/tools/m2/settings.xml -O .circleci/settings.xml
      - run: *jfrog-login
      - run:
          name: Maven deploy
          command: mvn deploy -s .circleci/settings.xml -DskipTests
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          context: global
      - deploy:
          context: global
          requires:
            - build
          filters:
            branches:
              only: master